### ISSUE TITLE
Some change in xml output from MAME is short circuiting our F5 import.

### ISSUE THREAD

**Issue by john-iv** [Mataniko/IV-Play#30] opened 2020-01-22 21:29 UTC
Something happened a few days ago in baseline MAME (via GitHUB) that broke our input routines w/ F5.
Usually when that happens other programs that rely on -lx or -listxml are broken too like clrmame.  But they appear to be fine.  MAME itself also produces a full 230MB XML file with -lx -listxml.

Our logs produced this:
1/22/2020 1:16:43 PM: An item with the same key has already been added.    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at IV_Play.XmlParser.MakeQuickDat()
   at IV_Play.MainForm.<RefreshGameList>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at IV_Play.MainWindow..ctor()

Any hints?  Thanks -

**Comment by Mataniko** [comment] 2020-01-22 23:59
This seems to imply that the new XML output has two machines with the same name. We can add a check on the XML parser to make sure this kind of use case is handled. I'll try to take a look and see what game is causing this as this could be unintended by MAME.

What version of MAME did this start happening with?

**Comment by Mataniko** [comment] 2020-01-23 00:17
This happens when doing the initial import (-listclones), but I can't seem to reproduce using the latest MAME nightly build.

**Comment by john-iv** [comment] 2020-01-23 01:24
I build clean baseline twice daily on a chron job, 6am and 6pm.  It started happening yesterday.  I'm now at
0.217 (mame0217-547-g819af3ced9)
and the problem continues to occur.  The full clean will start in 40 mins.
I've also done a conemu / pacman -Syu to update all the build tools in the MAME build package.

**Comment by Mataniko** [comment] 2020-01-23 01:55
Can you package the latest build and send it over?

**Comment by john-iv** [comment] 2020-01-23 02:01
Emailed.

**Comment by Mataniko** [comment] 2020-01-23 02:31
Closing this as a WONTFIX, machine names are unique, so this was a mistake on the author part for the `gigatron` driver. There should be a fix in MAME coming up soon, and this won't make it into an official release.

**Closed by Mataniko** 2020-01-23 02:31 UTC
Labels: bug

**Comment by john-iv** [comment] 2020-01-23 02:50
Does it make sense to harden the code to address this edge case if it comes up? Baseline MAME and clrmame for example don’t seem to have a problem functioning with this internal oversight, but we choke out.  Is it convoluted to do?

**Comment by Mataniko** [comment] 2020-01-23 11:27
I'm leaning towards no. This is bad input and we do want it to break here - if we do add some check what do we do? Add the first duplicate and ignore the second? Ask the user? Now we need to start tracking the "real" name and our non-duplicate name for search/filtering/etc. 

It will essentially require us to handle use cases for bad input further down the line, and could potentially add a slew of unnecessary bugs to fix.

**Comment by john-iv** [comment] 2020-01-23 19:16
Understood, was the log output sufficient in verbosity to finding the issue?

**Comment by Mataniko** [comment] 2020-01-23 19:28
It's verbose enough to tell exactly where the issue is:
```
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at IV_Play.XmlParser.MakeQuickDat()
```

Some basic error handling could be handled to at least give a more informative exception, like what game caused the issue, but just running in debug reveals it too.

**Comment by john-iv** [comment] 2020-01-23 20:05
Ok, thanks for checking this out.
